### ISSUE TITLE
[ERROR] Could not start MC Test Server.

### ISSUE THREAD

**Issue by joelcorey** [superjamie/minecraft-init-script#12]
I am fairly certain the error is from:

if server_running
    then
    echo " \* [OK] $SERVERNAME is now running (pid $JAVAPID)."
else
    echo " \* [ERROR] Could not start $SERVERNAME.
    exit 1
fi

I have gone through it several times and made sure that it is formatted correctly and as far as I can tell it is. The logic seems to be solid as well.

Help, please, if you are still paying attention to this.

Thanks!

**Comment by superjamie** [comment]
Hi, could you please put your initscript on a pastebin like pastie.org and provide the link here?

**Comment by joelcorey** [comment]
http://pastie.org/8235389

**Comment by superjamie** [comment]
Everything seems fine as far as the script goes. I'm able to run that jar file with that servicename in ~/test.server/

Do you have screen and all the other requirements installed?

Try running the Java invocation line directly and see if the server itself doesn't run:

`java -Xms2048M -Xmx4096M -Djava.net.preferIPv4Stack=true -XX:MaxPermSize=128M -XX:-DisableExplicitGC -XX:+UseParallelOldGC -XX:ParallelGCThreads=2 -XX:+AggressiveOpts -XX:+UseCompressedStrings -jar spigot.jar nogui`

I also released a new version of the initscript today, note the changes to `/etc/sysconfig/minecraft` if you're updating

**Comment by joelcorey** [comment]
Okay, I have the script in init.d on Centos 6. So I should move it to systemconfig?

**Comment by superjamie** [comment]
You'll need the script at `/etc/init.d/minecraft` and then a smaller settings file at `/etc/sysconfig/minecraft`. There are full instructions in the README and the script comments.

**Comment by joelcorey** [comment]
- Copy between the <<COMMENT and COMMENT lines and place the copy at /etc/sysconfig/minecraft
  If you need to edit settings, edit the /etc/sysconfig/minecraft file, not the initscript

First off thank you for your patience. Second, I do not understand what I am supposed to do here.

**Comment by superjamie** [comment]
Do the instructions you just pasted :) 

Download the initscript from [here](https://raw.github.com/superjamie/minecraft-init-script/master/minecraft) and save it to `/etc/init.d/minecraft` on your minecraft server

Copy the part of that file between:

```
## ---------------------------------------------------------
## copy between these lines and place them at /etc/sysconfig/minecraft
## do not include the <<COMMENT and COMMENT words
```

and:

```
## End of settings file
## ---------------------------------------------------------
```

then place that copy at `/etc/sysconfig/minecraft`. This new file is the config file.

In previous versions you had to define your configuration like `SERVERNAME` or `MCPATH` in the initscript itself. This meant that when a new version of the initscript came out, you had to update the initscript and then put all your changes in again, every time I updated the script. I found this tedious.

Now with this new way, you put your settings like `SERVERNAME` or `MCPATH` in the config file once and don't have to touch them again. This allows you to easily update the initscript when new versions come out.

**Comment by joelcorey** [comment]
I got it working for the most part. I believe it was either the java invocation not being supported by my CPU's or the naming of a directory with a "." in it. Anyway, it spits out the message that everything is working but when I type "screen -r <screennamehere>" it returns the error "Cannot open your terminal '/dev/pts/0' - please check."

This is getting a little outside of any error with your script so I will understand if you want to consider any issues resolved.

**Comment by joelcorey** [comment]
Alright, I apologize. I was sudoing into the minecraft user but to get to the screen session you actually have to logout completely and login as that user. 

Now it is giving me errors that it can't access the server.properties file and similar files. Hmmm.

**Comment by superjamie** [comment]
Try simplify the invocation down, just `java -jar spigot.jar nogui` should start on any system, then add parameters and see where Java trips up.

Note that this command runs without sizing the memory heap (-Xms and -Xmx). I don't know what the default memory sizes are, but I do know you will get pauses in the Java application as the heap resizes. This will be interpreted by your connected clients as server lag (like punching blocks and having them disappear later instead of instantly, slow loading of new map chunks, etc). So, one of the first things to try adding back in is -Xms and -Xmx.

The "Cannot open your terminal" thing happens to me when I logon as one user, then run the script as another user. I work around it with `chmod 777 /dev/pts/0`, or just always logon as the user who runs the script.

I'll mark this Closed but give me a yell if I can help more :)

**Comment by joelcorey** [comment]
I did a similar fix with chmod -R a+rw "server-directory"

All issues resolved, thank you very kindly for your assistance. Also, thank you for the script, it is excellent, if I make improvements I will be sure to share them.
