### ISSUE TITLE
/etc/sysconfig directory does not exist on ubuntu

### ISSUE THREAD

**Issue by Polhemic** [superjamie/minecraft-init-script#14]
The directory /etc/sysconfig does not exist on ubuntu (observed in 12.04.03 LTS). Maybe a better location would be /etc/minecraft/config ?

**Comment by Polhemic** [comment]
After exercising my google-fu a little more, a better alternative may be /etc/default/minecraft

**Comment by superjamie** [comment]
Agreed, I'll change this to `/etc/default/minecraft` next update. Thanks for your research too.

**Comment by superjamie** [comment]
SHA: d38bb4b5bf44f760ceb48b203b5349e2b4267e2a
