### ISSUE TITLE
[ERROR] Settings file /etc/sysconfig/minecraft does not exist. Can't run!

### ISSUE THREAD

**Issue by FShiwani** [superjamie/minecraft-init-script#16]
Hi,
Whenever I use any command(e.g minecraft start) it says this
[ERROR] Settings file /etc/sysconfig/minecraft does not exist. Can't run!

I tried using both root and minecraft user(my user is called minecraft not bukkit)

Centos 6 64BIT
1GB RAM VPS

**Comment by superjamie** [comment]
Please read the installation instructions here on GitHub and create the required file at `/etc/sysconfig/minecraft`.

**Comment by FShiwani** [comment]
Okay! Got rid of that issue, however after starting the minecraft server(minecraft start) and making sure it is running using top command, I am unable to see it in my client and when I try and join it, it gets stuck on Logging In.... and eventually says Internal Exception: java.net.SocketTimeoutException: Read Timed Out

**Comment by superjamie** [comment]
Cool. If you're able to run `minecraft status` or `minecraft info` and see the Minecraft server running, then the script is doing its job.

It sounds like you haven't opened the firewall port which your Minecraft server is running on. Your VPS provider should be able to assist with that.

**Comment by FShiwani** [comment]
Doesn't seem to be a port issue as when I disable IPTABLES I am still unable to connect. Also my VPS doesn't provide any support on these types of matters, I have to manually open the port through IPTABLES. Also, another thing is that I was able to connect to the server before without opening any firewall port.

**Comment by FShiwani** [comment]
Worked! For some reason the bukkit files were owned by root and the permissions were messed up, I did chown -R minecraft \* and it worked, your script is working perfectly. Nice Work and thanks for the support!

**Comment by superjamie** [comment]
Ah, excellent, glad to see things are all fixed :)
