### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by ice2921** [superjamie/minecraft-init-script#17]
I get the following errors when calling the script:

[bukkit@localhost ~]$ minecraft start
- CraftBukkit was not already running. Starting...
- Using map named "world"...
  bash: line 1: -XX:MaxPermSize=128M: command not found
  bash: line 2: -XX:+UseParallelOldGC: command not found
  bash: line 3: -XX:+AggressiveOpts: command not found
- Checking CraftBukkit is running...
- [ERROR] Could not start CraftBukkit.
  [bukkit@localhost ~]$

**Comment by Polhemic** [comment]
Any chance of a little more info?
Which platform are you on? (uname -a) Which version of java? Is it on your path?
If you could attach a copy of your /etc/sysconfig/minecraft that would help.

**Comment by ice2921** [comment]
Im sorry I should have been more clear im running CentOS 6.3 x64. I downloaded Java 7. I am not home right now, but will get more info when I get home tonight. Thanks for the reply.

**Comment by ice2921** [comment]
Im running the following java version:

[bukkit@localhost craftbukkit]$ java -version
java version "1.7.0_45"
Java(TM) SE Runtime Environment (build 1.7.0_45-b18)
Java HotSpot(TM) 64-Bit Server VM (build 24.45-b08, mixed mode)

Path appears to be set correctly as I can call java -version.
Here is a copy of my /etc/sysconfig/minecraft:
http://pastebin.com/yARSjp5A

**Comment by superjamie** [comment]
Ah, the INVOCATION (the command which is used to start the server) is spread across multiple lines:

```
INVOCATION="java -Xms1024M -Xmx1024M -Djava.net.preferIPv4Stack=true
-XX:MaxPermSize=128M -XX:UseSSE=3 -XX:-DisableExplicitGC
-XX:+UseParallelOldGC -XX:ParallelGCThreads=$CPU_COUNT
-XX:+AggressiveOpts -XX:+UseCompressedStrings -jar $SERVICE nogui"
```

Make it one line, like this:

```
INVOCATION="java -Xms1024M -Xmx1024M -Djava.net.preferIPv4Stack=true -XX:MaxPermSize=128M -XX:UseSSE=3 -XX:-DisableExplicitGC -XX:+UseParallelOldGC -XX:ParallelGCThreads=$CPU_COUNT -XX:+AggressiveOpts -XX:+UseCompressedStrings -jar $SERVICE nogui"
```

**Comment by ice2921** [comment]
So close. Now on the minecraft client I get the following message when trying to log on to the server: 
Exception:io.netty.handler.timeout.ReadTimeoutException

**Comment by superjamie** [comment]
Is the server running correctly? ie: you can `minecraft console` and it looks like it's got a world up?

Looking for this error on Google, it appears to be either a network issue, or some sort of incompatibility between the Minecraft client and server versions you're using. Definitely something outside this script.

Whilst I don't want to start to get into general Bukkit support, make sure you have the firewall port open (the default is TCP 25565), and use a tool like [MTR](http://en.wikipedia.org/wiki/MTR_%28software%29) to check for packet loss or high latency between yourself and the Minecraft server.

It also seems other people report this when their Minecraft server runs out of memory. Notice you've specified that your Minecraft process should use 1Gb RAM (`-Xms1024M -Xmx1024M`). You should probably have at least 1.5Gb or perhaps even 2Gb RAM.

**Comment by ice2921** [comment]
It turned out to be a version issue. Thanks for your help.

**Comment by superjamie** [comment]
Cool, thanks for letting me know!
