### ISSUE TITLE
Any interest in backup to AWS S3 feature?

### ISSUE THREAD

**Issue by Polhemic** [superjamie/minecraft-init-script#18]
I've got a separate script that performs offsite backups to Amazon Web Services S3 on my server. Is this a feature that people want? Would a pull request be looked on favourably?

**Comment by superjamie** [comment]
Hey thanks for the idea! I personally don't use S3, but I'm happy to leave this request open and see if there's sufficient demand.

Depending on the size and quality of the code, I could take a pull, or I'd be happy to be "official partners" and do some linking/integration of our separate scripts. See how we go with user response first.

**Comment by superjamie** [comment]
You may have seen @Mooash provided a patch in #24 which allows users to disable and enable just world-writes, which helps to integrate with third-party backup solutions.

The concept would be to set cron up like this:

```
service minecraft save-off
<point other backup command at world location>
service minecraft save-on
```

That seemed like a good solution to me, so I pulled the patch in.

**Comment by superjamie** [comment]
I'll close this off for now but please do reply if I can help more.
