### ISSUE TITLE
centos 6 error

### ISSUE THREAD

**Issue by gaddcasey1** [superjamie/minecraft-init-script#21]
on centOS 6 i the following error when i run chkconfig --add minecraft.

error reading information on service minecraft: No such device

**Comment by superjamie** [comment]
It appears the script file is not located at `/etc/init.d/minecraft`.

```
# chkconfig --add notaservice
error reading information on service notaservice: No such file or directory
# ll /etc/init.d/ | grep -c notaservice
0
```

**Comment by gaddcasey1** [comment]
thank you all fixed
