### ISSUE TITLE
Settings file not working

### ISSUE THREAD

**Issue by gaddcasey1** [superjamie/minecraft-init-script#22]
I cant seem to get the settings file to work.  i am running centOS 6 and i copy between the lines and paste it in a new file at /etc/default/minecraft. i run minecraft start and i get these errors:

[root@localhost ~]# minecraft start
: command not foundaft: line 2:
: command not foundaft: line 5:
: command not foundaft: line 8:
: command not foundaft: line 11:
: command not foundaft: line 14:
: command not foundaft: line 17:
: command not foundaft: line 20:
: command not foundaft: line 23:
: command not foundaft: line 26:
: command not foundaft: line 29:
: command not foundaft: line 31:
: command not foundaft: line 34:
: command not foundaft: line 38:
: command not foundaft: line 41:
: command not foundaft: line 44:
: command not foundaft: line 48:
- [ERROR] Settings file /etc/default/minecraft is not applying. Can't run!
  Check your options are uncommented and you haven't copied the <<COMMENT block.

the lines seem to be where ever there is a blank space so i removed the spaces and i get this:

 [ERROR] Settings file /etc/default/minecraft is not applying. Can't run!
 Check your options are uncommented and you haven't copied the <<COMMENT block.

here is my settings file

![image](https://cloud.githubusercontent.com/assets/5962334/3560673/faf63158-0981-11e4-8067-b834ed4bea95.png)

**Comment by superjamie** [comment]
Did you create the settings file on Windows, then upload it to your Linux system?

Windows and Linux have different line endings. You can't see this in a text editor, but Linux saves text files with a "LF" (line feed), and Windows saves text files with a "CR+LF" (carriage return and line feed). I wonder if this is messing up the script.

I'd like to convert the settings file from Windows line endings to Linux line endings.

Install a tool which can convert the line endings with `yum install dos2unix`

Then convert the line endings with `dos2unix /etc/default/minecraft`

In future you might want to save files for your Linux box with the Linux line endings. The [Edit Pad Lite](http://www.editpadlite.com/) text editor can do this. Alternately, work only in Linux and edit text files with `vim` or `nano`.

Let me know how you go.

**Comment by gaddcasey1** [comment]
all fixed thankyou
