### ISSUE TITLE
I get an error when trying to run "minecraft console" on ubuntu server 14

### ISSUE THREAD

**Issue by ghost** [superjamie/minecraft-init-script#25]
The error is Cannot open your terminal '/dev/pts/0' - please check.

**Comment by ghost** [comment]
I just realized that i can run it fine when I am logged in as the user "bukkit". Is there any way to make it so I do not have to be?

**Comment by superjamie** [comment]
The user running screen (so `bukkit`) and the root user have access to the `/dev/pts` device for a screen session.

You can give other users access by applying regular file/group permissions to the device file.

If you want everyone to be able to attach to the console, `sudo chmod 777 /dev/pts/0` should do the trick.

**Comment by superjamie** [comment]
Closing for now, please reply back if I can assist more.
