### ISSUE TITLE
The Screen plays Hide & Seek

### ISSUE THREAD

**Issue by ghost** [superjamie/minecraft-init-script#32]
Hello guys !
I've got a problem, your Script can't start with my OS (Ubuntu Server 14.04) !
We can see this error in boot.log : 
Cannot make directory '/var/run/screen': Permission denied

Google thinks that I use : 
sudo /etc/init.d/screen-cleanup start
If I add this line in your Script, it works ! BUT : The Screen doesn't exist !!!
Why ?!?
And if I add : sleep 1, we have the same problem ?
What do you think ? Have you an Idea ?
Thanks.

**Comment by superjamie** [comment]
Yes, several other Issues say the same thing. It seems Ubuntu's init is broken. I have some stuff to try to work around it, I just haven't had time yet. I'm going to close this one as a duplicate.
