### ISSUE TITLE
SETTINGSFILE gets wrong name on system boot

### ISSUE THREAD

**Issue by andrewkreid** [superjamie/minecraft-init-script#34]
I realise this script has been retired. Just thought I'd leave a note for those who come after me and have the same problem.

On RHEL-derived systems at least (don't know about Ubuntu etc.), the init script can fail to start on system boot. The reason is the following line (110)

```
SETTINGSFILE="/etc/default/$(basename $0)"
```

On boot, this resolves to something like `/etc/default/S85minecraft`, not `/etc/default/minecraft`. Since this file doesn't exist, the server doesn't start.

**Comment by superjamie** [comment]
Thanks for your comment, I too hope others find it useful.
