### ISSUE TITLE
Backup The Nether and The End

### ISSUE THREAD

**Issue by Icarus-xx** [superjamie/minecraft-init-script#6]
Backup should detect The Nether and The End if they exist.

**Comment by superjamie** [comment]
I really like this idea. Looks like they are always called "_nether" and "_the_end" so it should be easy to detect and backup if present.

**Comment by Icarus-xx** [comment]
Indeed the nether and the end worlds are always named with "_the_nether" and "_the_end" at the end of the directory.

**Comment by superjamie** [comment]
Added in commit 64b36c7680cea911d1426f8af9931afcf16dbacb. Please re-open this issue if it's not working for you.
