### ISSUE TITLE
Multiple server support

### ISSUE THREAD

**Issue by Icarus-xx** [superjamie/minecraft-init-script#7]
As it is mentionned in the title, it would be great to have a multi-server startup script.
Actually copying the script for each server raise the maintenance costs.

**Comment by superjamie** [comment]
When I first had the request to implement multiple server support, I looked into a few different ways to do this. One can easily find existing examples of deluge-daemon and redis-server which allow for multiple instances.

However, these all involve breaking into many separate config files with specific syntax, arrays of separate servers to control, and involve starting and stopping all the daemons at once.

The requirements I was given were control of each map as a separate entity. I couldn't think of a way to allow control of individual maps without introducing a longer syntax of commandline options, and I consider the current simple syntax to be a strength of the script.

The simplicity of the current script's code is also a strength. I've had a fair few users fix issues themselves and give me the fix too. I think large numbers of arrays, syntax, and config files would obfuscate the code and make it harder for people to help themselves.

I looked at professional ways to do this. The Red Hat Knowledgebase suggests to duplicate the initscript. The Linux Standards Base defines the service by the Provides line in the init info, so a separate service should be a separate script with a separate Provides.

Initially I wanted to implement separate server control in one file too, but I eventually moved to improving the logic to detect multiple instances in server_running() and having the user create separate script files.

If you can think of a good way to implement this in one file whilst addressing the concerns I found myself facing, I'll consider it, but for now I'll stick to the current method of duplicating the script.

**Comment by confuser** [comment]
@superjamie with the new settings file, for multiple servers, we still have to duplicate the script? Might it be an idea to set the settings file path within the minecraft alias command itself as an arugment? That would remove the need to duplicate the script and give more control over which settings the commands relate to.

**Comment by superjamie** [comment]
Yes, you'll need to duplicate both the script and the settings file. I've added some logic with 1381f1483effcc569d767262a25de2a14d588167 to take the name of the settings file from the name of the script.
