### ISSUE TITLE
BungeeCord server support

### ISSUE THREAD

**Issue by Icarus-xx** [superjamie/minecraft-init-script#8]
I would be great to also support BungeeCord proxy.

It should not be hard, maybe using a flag to tell that you run Bungee to limit some commands.

**Comment by superjamie** [comment]
I have not heard of this before so I did a bit of reading. From what I understand, BungeeCord is a Java app which acts as a gateway and proxies your connection to one or multiple backend Spigot servers.

Either the BungeeCord server or those other Spigot servers run a plugin which allows players to use commands or warp gates (much like entering The Nether) to travel between the backend servers without the player having to disconnect and reconnect.

The only difference I can see is that BungeeCord doesn't have a server.properties (it has a config.yml instead) so there is no "world" to backup, and the script would have to find the "host" section in config.yml to identify the port which BungeeCord is running on.

Is that right?

**Comment by Icarus-xx** [comment]
BungeeCord is only a proxy. It does not need plugins or Spigot to be run on the Minecraft servers.

Spigot is a Bukkit on steroids :) with Bukkit compatibility.

Afaik, there is no console in BungeeCord (only online "/commands") so to terminate the process you have to kill it.

**Comment by confuser** [comment]
Not true, it does have a console. To stop it you use the end command rather
than stop.

**Comment by superjamie** [comment]
I considered this but I'm not really keen to add support for more server software. Vanilla and Bukkit only. If you're interested in writing and maintaining the patches I'll consider it. You are also welcome to fork and create your own BungeeCord script.
